export const QUESTIONS_START: string[] = [
  "Vilken hobby önskar du att du hade mer tid för?",
  "När ändrade du senast åsikt om något?",
  "Om du kunde forska om ett ämne på heltid, vilket skulle du välja?",
  "Vilken titel skulle du ge det här kapitlet i din livshistoria?",
  "Vad är ett roligt men pinsamt minne du har från uppväxten?",
  "Vilken var en av dina favoritdagar den senaste månaden, och varför?",
  "Vilka aktiviteter eller miljöer väcker mest glädje hos dig?",
  "Vilken plats betyder mycket för dig, och varför är den så speciell?",
  "Vilken bok, förutom Bibeln, tycker du att alla borde läsa?",
  "Vilken enkel glädjekälla har du i vardagen?",
  "Är du mer en som spenderar eller sparar pengar?",
  "Vad är en av dina favoritaktiviteter på en ledig dag?",
  "Om du kunde äta middag med en person, levande eller död (förutom Jesus), vem skulle det vara och varför?",
  "Vad ångrar du att du slutade med, eller vad önskar du att du hade slutat med tidigare?",
  "Vilken egenskap värdesätter du mest hos en vän?",
  "Vilket äventyr på din önskelista hoppas du få uppleva en dag?",
  "Vad var det senaste ögonblicket som fyllde dig med förundran?",
  "Om du skulle hålla en 15-minuters presentation om vad som helst, vilket ämne och vilken titel skulle du välja? Var kreativ.",
  "Om du var en karaktär i en film, vilken karaktär skulle du vara, och i vilken film?",
  "Vilken annan stad eller land skulle du kunna se dig bo i, och varför?",
  "Vilken orättvisa eller fråga engagerar dig starkt?",
  "Inom vilket ämne skulle du säga att du har mest kunskap?",
  'Vad är en av dina märkligaste "grejer" som stör dig?',
  "Vilken känsla har du känt mest den här veckan, och varför?",
  "Vad är du nyfiken på just nu?",
  "Om du kunde bevittna en historisk händelse, vilken skulle du välja?",
  "Vilket minnesvärt råd har du fått?",
  "Vad är en av dina stoltaste prestationer, stor eller liten?",
  "Om du kom med en varningstext, vad skulle den säga?",
  "Om du vann på lotteriet, vad skulle du göra med pengarna?",
  "På vilket litet sätt har du bidragit till någon annans glädje eller välmående på senaste tiden?",
  'Vilka är några saker på din personliga "må-bra-lista"?',
  "Vilken är den mest minnesvärda gåvan du fått?",
  "Vilket konstverk (målning, arkitektur, skulptur, film osv.) berör dig, och varför?",
  "Berätta om en gång någon var generös mot dig. Vem var det, och vad hände?",
  "Vilken påhittad värld skulle du helst vilja leva i, och varför?",
  "Om du kunde skriva en bok tillsammans med en författare, förr eller nu, vem skulle det vara, och vad skulle boken handla om?",
  "Om Gud skulle svara på en fråga från dig idag, vilken skulle det vara?",
  "Om du skulle visa runt någon i din hemstad, vart skulle du ta dem först som betyder något för dig?",
  "Vilken är den bästa konsert du varit på, och varför?",
  "Om du bara fick använda tre ord för att beskriva din familj, vilka skulle det vara?",
  "Vilken är din favoritplats du rest till, och varför?",
  "Hur uttrycker du naturligast kärlek till de du bryr dig om?",
  "Vad är en liten eller enkel sak du vill vara mer tacksam för?",
  "Under vilka omständigheter visar du dig från din bästa sida? Och din sämsta?",
  "Vilken berättelse i evangelierna berör dig mest?",
  "Vilken person i evangelierna känner du mest igen dig i, och varför?",
  "Vad lär du dig om dig själv just nu?",
  "Vad har nyligen förändrats till det bättre i ditt liv?",
  "Vilken irrationell rädsla hade du som barn?",
];

export const QUESTIONS_DEEP: string[] = [
  "Vilket mönster från din uppväxtfamilj hoppas du bära vidare, och vilket hoppas du lämna bakom dig?",
  'Vem är en av dina "hjältar" (nära eller på avstånd), och vad beundrar du mest hos dem?',
  "Avsluta meningen: Jag håller på att lära mig acceptera ______.",
  "Vad försöker du avlära dig just nu?",
  "Vilken uppmuntran fick du senast som verkligen betydde något för dig?",
  "Vad hoppas du att dina nära och kära säger om dig när du dör?",
  "Vilken svår upplevelse ogillade du först men är tacksam för nu?",
  "Vilken av Jesu undervisningar tycker du är svårast att förstå eller leva ut?",
  "Vem stod du närmast i din familj som barn, och hur har den relationen förändrats eller förblivit densamma?",
  "Var i syskonordningen är du, och hur tror du det format dig som person?",
  "Hur har du upplevt förlåtelsens kraft, genom att ge eller ta emot den?",
  "Vad tror du ditt yngre jag skulle beundra hos dig idag?",
  "Om ditt framtida jag kunde ge dig råd inför den kommande tiden, vad tror du de skulle säga?",
  "Vad vill du släppa taget om i år?",
  "Vilken var en stor vändpunkt i ditt liv?",
  "Vilken egenskap eller hållning hos Jesus önskar du mest att gestalta?",
  "Vad skulle du kunna ångra om tio år om livet fortsätter som nu, och vad kan du göra åt det redan idag?",
  "Vilken längtan har du som du väntar på att få se uppfylld?",
  "Om din vecka var ett ljus, brinner lågan starkt, svagt eller något mittemellan? Varför?",
  "Vilken utmaning från din ungdom visar sig fortfarande i ditt liv idag?",
  "Vilken lögn kämpar du för att inte tro på?",
  "Vilket är ditt favoritögonblick med ditt barn (eller som du minns med dina föräldrar)?",
  "Vad gillar du mest med dig själv?",
  "Vilken bön har blivit besvarad, och vilken väntar fortfarande på svar, det senaste året?",
  "Vem har format och påverkat dig mest i livet, förutom Jesus, och hur?",
  "Om vi frågade en god vän till dig, vilka värderingar skulle de säga att du lever efter mest?",
  "Vilka platser eller vanor ger din själ den djupaste vilan just nu?",
  "När kände du dig senast vilsen eller ensam?",
  "På vilket område i ditt liv bjuder Gud in dig till djupare offer och osjälviskhet?",
  "Vilken egenskap hos någon i den här gruppen beundrar du?",
  "Vilken vana vill du bryta, och vilken vill du bygga upp, i år?",
  "På vilket område i ditt liv känner du dig minst fri?",
  "Känner du dig lugn just nu? Varför eller varför inte?",
  "Inom vilket område känner du den största klyftan mellan den du är och den Jesus bjuder in dig att bli?",
  "Vad undviker du just nu i ditt liv – en person, ett beslut, ett problem – och varför?",
  "Vilka sidor av dig kommer fram när du känner dig mest trygg och som dig själv?",
  "Vilken utmaning brottas du med just nu som kräver Guds hjälp?",
  "Vilket ord beskriver bäst hur du vill att andra ska uppleva dig?",
  "Vilken sanning om Gud har du svårt att tro på just nu?",
  "Vilka egenskaper hade du som barn som fortfarande stämmer på dig idag, eller som du tappat?",
  "Vilka antaganden gör folk ibland om dig som inte är sanna?",
  "Vilket ord, uttryck eller bild från Bibeln vägleder dig genom den här perioden i livet?",
  "På vilket sätt känner du behov av att växa på ett sätt som går emot din personlighet?",
  "Om du kunde återuppleva ett barndomsminne, vilket skulle det vara?",
  'Har du någon gång gått igenom en period som kändes som "en öken"? Om så, vad lärde du dig?',
  "Hur visar sig rädsla mest i ditt liv just nu?",
  "Under vilken period i ditt liv kände du dig mest levande, och varför?",
  "Vilken händelse har format vem du är idag?",
  "Vilka delar av att följa Jesus känns mest naturliga, och vilka känns mest onaturliga, för dig?",
  "Om du visste att det var din sista dag, vad skulle du sluta prioritera som du idag tycker är viktigt?",
];

export type QuestionCategory = "start" | "deep" | "mix";

export function getQuestionPool(category: QuestionCategory): string[] {
  if (category === "start") return QUESTIONS_START;
  if (category === "deep") return QUESTIONS_DEEP;
  return QUESTIONS_START.concat(QUESTIONS_DEEP);
}

export function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
